### ISSUE TITLE
How to use two DACs at the same time in ATtiny 3216?

### ISSUE THREAD

**Issue by svchnik** [MicrochipTech/TB3210_Getting_Started_with_DAC#1]
I want to use DAC0 and DAC1 in ATtini 3216 but I only hear DAC0?
`
void VREF_init(void){

      VREF.CTRLA |= VREF_DAC0REFSEL_4V34_gc;       // Voltage reference at 4.34V

      //VREF.CTRLC |= VREF_DAC1REFSEL_4V34_gc;    // datasheet 31.3.1  For DAC1, use DAC1REFSEL in VREF.CTRLC ?

      VREF.CTRLB |= VREF_DAC0REFEN_bm;                // DAC0 reference enable: enabled

      VREF.CTRLB |= VREF_DAC1REFEN_bm;                // DAC1 reference enable: enabled ?

      _delay_us(VREF_STARTUP_MICROS);                    // Wait VREF start-up time

}
//-------------------------------------------------------
void DAC_init(void){

      PORTA.PIN6CTRL &= ~PORT_ISC_gm;                                  // Disable digital input buffer

      PORTA.PIN6CTRL |= PORT_ISC_INPUT_DISABLE_gc;

      PORTA.PIN6CTRL &= ~PORT_PULLUPEN_bm;                      // Disable pull-up resistor

      DAC0.CTRLA = DAC_ENABLE_bm | DAC_OUTEN_bm | DAC_RUNSTDBY_bm;     // Enable DAC, Output Buffer, Run in Standby

      DAC1.CTRLA |= DAC_ENABLE_bm;

}
//...
//use
while (1){

          DAC0.DATA = myWaveA[myCounterA];              
          DAC1.DATA = myWaveB[myCounterB];              // NO SOUND !
          _delay_us(5);
}
`

**Comment by svchnik** [comment]
Only DAC0 has an output driver for an external pin.

**Comment by Dradnats** [comment]
@svchnik , for future reference this is documented in the DAC chapter as a note.

![image](https://user-images.githubusercontent.com/10521946/141771452-0a9aadb5-c64d-4744-aaa7-4b35d649355b.png)

https://ww1.microchip.com/downloads/en/DeviceDoc/ATtiny3216-17-DataSheet-DS40002205A.pdf
